- hosts: all
  tasks:

  - name: Download CUDA keyring
    ansible.builtin.get_url:
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
      dest: /tmp/cuda-keyring_1.1-1_all.deb

  - name: Install CUDA keyring
    ansible.builtin.apt:
      deb: /tmp/cuda-keyring_1.1-1_all.deb

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install CUDA toolkit
    ansible.builtin.apt:
      name: cuda-toolkit-12-6
      state: present

  - name: Install CUDA drivers
    ansible.builtin.apt:
      name: cuda-drivers
      state: present

    
  - name: 1. reboot after CUDA
    reboot:
      post_reboot_delay: 60

  - name: Wait for system to become reachable again
    wait_for_connection:
      delay: 20
      timeout: 300

  - name: Create directory for apt keyrings
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download Docker GPG key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

  - name: Add Docker repository
    ansible.builtin.shell: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  
  - name: Install ca-certificates and curl
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
      state: present

  - name: Create directory for apt keyrings
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download Docker GPG key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install Docker packages
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Install NVIDIA container toolkit
    ansible.builtin.apt:
      name: nvidia-container-toolkit
      state: present

  - name: Configure NVIDIA runtime
    ansible.builtin.shell: |
      nvidia-ctk runtime configure --runtime=docker

  - name: Restart Docker service
    ansible.builtin.systemd:
      name: docker
      state: restarted
  
  - name: Run Docker to check CUDA version
    ansible.builtin.shell: docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
    register: docker_output

  - name: Ensure CUDA and driver are present
    ansible.builtin.assert:
      that:
        - '"Driver Version" in docker_output.stdout'
        - '"CUDA Version" in docker_output.stdout'
      fail_msg: "Either CUDA or the driver version is not present."
      success_msg: "Both CUDA and the driver version are present."


